### ISSUE TITLE
add GMW and KBA

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/wdpa-pipelines#2]
Hi @goergen95, I'd like to add the mangroves and key biodiv area indicators to this repo.
Can I just go ahead and do that or would that interfere with anything you're doing at the moment?

**Comment by goergen95** [comment]
Its alright! Please go ahead! :)

**Comment by goergen95** [comment]
Also note that I just update `main` and `dev` branch of `mapme.indicators`. The `dev-gdal` branch is now merged into `dev` and should no longer be used.

**Comment by karpfen** [comment]
Good to know, thanks!
