### ISSUE TITLE
Include ODP portfolio

### ISSUE THREAD

**Issue by karpfen** [mapme-initiative/wdpa-pipelines#4]
Currently we only use the `fz_info_portfolio` column. I think we should actually change this up to include `bmz_portfolio`, `odp_portfolio` and `fz_info_portfolio`, because those three make up the "KfW Portfolio".

https://github.com/mapme-initiative/wdpa-pipelines/blob/ad39891ab090860842959aa6f46a5e078e61cd04/src/003_regions.R#L3

**Comment by goergen95** [comment]
Hi, I actually updated the repo yesterday and the `regions` script is no longer included. My idea was to develop this repo into CLI scripts for indicators which are governed by [`config.yml`](https://github.com/mapme-initiative/wdpa-pipelines/blob/main/config.yml) and maybe some command line arguments (respectively). In that sense, prepping the input geometries is out of scope for this repo. I'd guess we should find another place to live for scripts for these internal stuff. Any thoughts?

**Comment by karpfen** [comment]
Cool, I think that's a good way to go.
How would the indicator selection and parametrization work in this case? A section in the yml or something different?

Regarding pre and post-processing of data outside the pipeline: Should we just put it in another folder here in the repo or do you have something different in mind?
I'm also working on a script right now that takes the pipelines result and selects/reshapes it into the format we use for the portfolio on the ODP. And currently I'm not sure where this should go in the end. Until now, I put those things in the `mapme.ETL` repo.

**Comment by goergen95** [comment]
I would not like to mix up organization internal stuff in this repo. So, I guess `mapme.ETL` or similar is the right place to go for such things.

My current idea was that you set some config options in the `yml`. Then you would call for example something like: 
```bash
Rscript gfw.R --min-cover 30 --min-size 1.0 --input my-polys.gpkg
```
